In [5]:
import numpy as np
import pandas as pd
import scipy
import re
import os
from pathlib import Path

Raw datasets downloaded from https://mjl.clarivate.com/collection-list-downloads

on 13 May 2026

(according to WoS, last updated 20 April 2026)

In [7]:
data_path = Path('../data/260513_wos_cc/')
os.listdir(data_path)
#pd.read_csv()

['Arts & Humanities Citation Index (AHCI).csv',
 'Emerging Sources Citation Index (ESCI).csv',
 'JCR 2025.csv',
 'JOURNAL_CHANGE_MONTH_2026_01.xlsx',
 'JOURNAL_CHANGE_MONTH_2026_02.xlsx',
 'JOURNAL_CHANGE_MONTH_2026_03.xlsx',
 'JOURNAL_CHANGE_MONTH_2026_04.xlsx',
 'JOURNAL_CHANGE_YEAR_2023.xlsx',
 'JOURNAL_CHANGE_YEAR_2024.xlsx',
 'JOURNAL_CHANGE_YEAR_2025.xlsx',
 'Science Citation Index Expanded (SCIE).csv',
 'Social Sciences Citation Index (SSCI).csv']

In [21]:
# current collection

collect = []
for filename, collection in zip(['Arts & Humanities Citation Index (AHCI).csv',
 'Emerging Sources Citation Index (ESCI).csv',
 'Science Citation Index Expanded (SCIE).csv',
 'Social Sciences Citation Index (SSCI).csv'], 
                    ['AHCI', 'ESCI', 'SCIE', 'SSCI']):
    df = pd.read_csv(str(data_path) + '/' + filename)
    df['collection'] = collection
    collect.append(df)
df_current = pd.concat(collect)

In [65]:
# past collection

collect = []
for filename in ['JOURNAL_CHANGE_MONTH_2026_01.xlsx',
 'JOURNAL_CHANGE_MONTH_2026_02.xlsx',
 'JOURNAL_CHANGE_MONTH_2026_03.xlsx',
 'JOURNAL_CHANGE_MONTH_2026_04.xlsx',
 'JOURNAL_CHANGE_YEAR_2023.xlsx',
 'JOURNAL_CHANGE_YEAR_2024.xlsx',
 'JOURNAL_CHANGE_YEAR_2025.xlsx']:
    df = pd.read_excel(str(data_path) + '/' + filename)
    df['source_filename'] = filename
    collect.append(df)
df_changes = pd.concat(collect)
df_changes.columns = list(pd.read_excel(str(data_path) + '/' + filename, header=27).columns) + ['source_filename']
df_changes = df_changes.dropna(subset=['Journal title'])

prohib = ['Journal title',
          'The Master Journal List is available online here ', 
          'Details of our journal evaluation process and selection criteria are available here']
df_changes = df_changes.loc[~df_changes['Journal title'].isin(prohib)].copy()

In [66]:
df_changes

,Journal title,ISSN,eISSN,Publisher name,Web of Science Core Collection,Coverage change,Notes,source_filename
24,REVISTA INTERAMERICANA DE BIBLIOTECOLOGIA,0120-0976,2538-9866,UNIV ANTIOQUIA,Emerging Sources Citation Index,Accepted,NaN,JOURNAL_CHANGE_MONTH_2026_01.xlsx
25,QUALITATIVE SOCIOLOGY REVIEW,1733-8077,1733-8077,LODZ UNIV PRESS,Emerging Sources Citation Index,Accepted,NaN,JOURNAL_CHANGE_MONTH_2026_01.xlsx
26,HISTORY STUDIES,1309-4688,1309-4173,OSMAN KOSE,Emerging Sources Citation Index,Accepted,NaN,JOURNAL_CHANGE_MONTH_2026_01.xlsx
27,PROCEEDINGS OF THE AMERICAN MATHEMATICAL SOCIE...,NaN,2330-1511,AMER MATHEMATICAL SOC,Emerging Sources Citation Index,Accepted,NaN,JOURNAL_CHANGE_MONTH_2026_01.xlsx
28,TRANSACTIONS OF THE AMERICAN MATHEMATICAL SOCI...,NaN,2330-0000,AMER MATHEMATICAL SOC,Emerging Sources Citation Index,Accepted,NaN,JOURNAL_CHANGE_MONTH_2026_01.xlsx
...,...,...,...,...,...,...,...,...
700,MARKET MICROSTRUCTURE AND LIQUIDITY,2382-6266,2424-8037,WORLD SCIENTIFIC PUBL CO PTE LTD,Emerging Sources Citation Index,Cease,NaN,JOURNAL_CHANGE_YEAR_2025.xlsx
701,ANUARIO CIDOB DE LA INMIGRACION,2462-6732,2462-6740,FUNDACIO CIDOB,Emerging Sources Citation Index,Cease,NaN,JOURNAL_CHANGE_YEAR_2025.xlsx
702,EUROPEAN INTEGRATION STUDIES,1822-8402,2335-8831,KAUNO TECHNOLOGIJOS UNIV,Emerging Sources Citation Index,Cease,NaN,JOURNAL_CHANGE_YEAR_2025.xlsx
703,TECHNICAL COMMUNICATION,0049-3155,NaN,SOC TECHNICAL COMMUNICATION,Social Sciences Citation Index,Cease,NaN,JOURNAL_CHANGE_YEAR_2025.xlsx
704,MECHANICAL ENGINEERING,0025-6501,1943-5649,ASME,Science Citation Index Expanded,Other,NaN,JOURNAL_CHANGE_YEAR_2025.xlsx

In [53]:
df_changes

,Journal title,ISSN,eISSN,Publisher name,Web of Science Core Collection,Coverage change,Notes
23,Journal title,ISSN,eISSN,Publisher name,Web of Science Core Collection,Coverage change,Notes
24,REVISTA INTERAMERICANA DE BIBLIOTECOLOGIA,0120-0976,2538-9866,UNIV ANTIOQUIA,Emerging Sources Citation Index,Accepted,NaN
25,QUALITATIVE SOCIOLOGY REVIEW,1733-8077,1733-8077,LODZ UNIV PRESS,Emerging Sources Citation Index,Accepted,NaN
26,HISTORY STUDIES,1309-4688,1309-4173,OSMAN KOSE,Emerging Sources Citation Index,Accepted,NaN
27,PROCEEDINGS OF THE AMERICAN MATHEMATICAL SOCIE...,NaN,2330-1511,AMER MATHEMATICAL SOC,Emerging Sources Citation Index,Accepted,NaN
...,...,...,...,...,...,...,...
702,EUROPEAN INTEGRATION STUDIES,1822-8402,2335-8831,KAUNO TECHNOLOGIJOS UNIV,Emerging Sources Citation Index,Cease,NaN
703,TECHNICAL COMMUNICATION,0049-3155,NaN,SOC TECHNICAL COMMUNICATION,Social Sciences Citation Index,Cease,NaN
704,MECHANICAL ENGINEERING,0025-6501,1943-5649,ASME,Science Citation Index Expanded,Other,NaN
707,The Master Journal List is available online here,NaN,NaN,NaN,NaN,NaN,NaN
708,Details of our journal evaluation process and ...,NaN,NaN,NaN,NaN,NaN,NaN